#--------------PLUGIN CREATED BY HAXY972-------------------------
# Messages relatifs au plugin


# IMPORTANT: Pour le nom des équipes veuillez ajouter les groupes suivants dans votre GroupManager: "Rouge", "Bleu", "Vert", "Jaune", "Mort" et "Joueur"
# Il vous suffira ensuite avec d'ajouter des permissions NameTagEdit à ces groupes.
# Les roles seront automatique détecté par le plugin et donné au joueur si vous ACTIVEZ CETTE FONCTIONNALITEE.
grades: true

messages:
  prefix: "&6&lFallen&b&lKingdom&8» "


# Laisse la team Jaune en vie au début de la game (Utile si un seul joueur pour tester)
debug: false
#--------------PARTIE-------------------------

# Il faut mettre le nombre de joueurs nécessaires au lancement de la partie.
partie:
  world: "world"

  # Nombre de secondes pour le Timer
  timer: 30
  # Nombre de joueur requis pour démarrer la partie
  requiredtostart: 20


  # Jour auquel la partie démarre
  jour-de-depart: 1
  # La durée d'un jour est exprimée en SECONDES*
  jour-duree: 600
  # A partir de ce jour les joueurs peuvent perdre de la nourriture (Barre de faim)
  jour-de-faim: 3
  # A partir de ce jour les assaults peuvent commencer
  jour-de-pvp: 5
  # A partir de ce jour les joueurs peuvent se taper
  jour-de-pvp-2: 3
  # A partir de ce jour les coffres du middles sont remplis
  jour-de-coffre: 2
  # A partir de ce jour le nether est activé
  jour-nether: 2
  # A partir de ce jour les beacons de chaque équipe sont détruits
  jour-bed-destroyed: 8

  # Active/Desactive les craft customs
  custom-craft: true

#--------------TEAM & SPAWN-------------------------
#ACTIVER OU DÉSACTIVER DES ÉQUIPES
teams:
  max-players-per-team: 5
  rouge: true
  bleu: true
  vert: true
  jaune: true

# Différents spawns

locations:
  #LES COORDONÉES DU LOBBY DOIVENT FINIR PAR .500
  lobby:
    x: -39.500
    y: 210
    z: 95.500
    yaw: -1
    pitch: 2
  #rayon de bloc pour le tp automatique
  rayon: 50

  # SPAWNS DES DIFFÉRENTES ÉQUIPES
  spawn-rouge:
    x: 278.569
    y: 67
    z: 66.514
    yaw: 88
    pitch: 0
  spawn-bleu:
    x: -192.520
    y: 67
    z: -185.503
    yaw: -3
    pitch: -6
  spawn-vert:
    x: -205.521
    y: 69
    z: 297.479
    yaw: 177
    pitch: -3
  spawn-jaune:
    x: -295.404
    y: 63
    z: 77.616
    yaw: -86
    pitch: -4

  # BEACONS DES DIFFÉRENTES ÉQUIPES

  beacon-rouge:
    x: 278.500
    y: 65
    z: 66.500
  beacon-bleu:
    x: -192.500
    y: 65
    z: -185.500
  beacon-vert:
    x: -205.500
    y: 67
    z: 297.500
  beacon-jaune:
    x: -295.500
    y: 61
    z: 77.500





# ZONES DES DIFFERENTS EQUIPES

regions:
  # La marge est la zone prise en plus de la regions et défini l'endroit ou les joueurs ne peuvent pas poser de blocs (DEFAUT -> 10 blocs).
  # Cela évite de monter dans la base de l'autre avec des blocs par exemple.
  marge: 10
  teams:
    # Le territoire de chaque équipe forme un carré, relevez les deux coordonées X du bords des carrés ainsi que les coordonées Z
    # La plus petite valeur va dans min* et la plus grande dans max*, cela formera un carré.

    rouge:
      min-x: 264.500
      max-x: 293.500
      min-z: 51.500
      max-z: 80.500

    bleu:
      min-x: -206.500
      max-x: -178.500
      min-z: -200.500
      max-z: -172.500
    vert:
      min-x: -219.500
      max-x: -190.500
      min-z: 282.500
      max-z: 311.500
    jaune:
      min-x: -309.500
      max-x: -281.500
      min-z: 62.500
      max-z: 90.500

    # Si le joueur entre dans les zones énumérées juste au-dessus il sera téléporté dans la zone qui lui correspond
    # donc s'il rentre dans la zone rouge il sera tp a "tp-rouge".
    tp-rouge:
      x: 251.699
      y: 67
      z: 68.946
      yaw: -95
      pitch: -4
    tp-bleu:
      x: -193.385
      y: 68
      z: -161.445
      yaw: -179
      pitch: -0
    tp-vert:
      x: -205.579
      y: 69
      z: 271.643
      yaw: 0
      pitch: -2
    tp-jaune:
      x: -269.913
      y: 63
      z: 78.701
      yaw: 93
      pitch: -2


#--------------Options-------------------------

#Barrière dans l'inventaire
options:
  barrier: false