name: FallenKingdom
version: 1.0
author:
main: fr.haxy972.fallen.Main
commands:
  forcestart:
    description: Demarrer la partie de force
    permission: fallen.timer
  nextday:
    description: Avancer la partie d'un jour
    permission: fallen.daycontrol
  previousday:
    description: Reculer la partie d'un jour
    permission: fallen.daycontrol
  reset:
    description: ez
  stats:
    description: Voir vos statistique en cours de jeu
    aliases: statistiques, statistique


